### ISSUE TITLE
Also rebase static imports?

### ISSUE THREAD

**Issue by taylor-hunt-kr** [kim366/rollup-plugin-base-url#1]
I found this plugin when trying to get root-relative paths for static imports, for inlining very small scripts:

```marko
<if(assets.jsEntry.code.length > 1024)>
  <script async type="module">$!{assets.jsEntry.code}</script>
</if>
<else>
  <script async type="module" src=`/_/${assets.jsEntry.fileName}`/> 
</else>
```

The problem is that inlining changes the parent URL of the JS code, so it breaks `import`s of `./`-relative URLs. Here’s one of those tiny scripts from my project:

```js
import{r as s,i as e,o as r}from"./site-7b9abd64.js";import"./Stepper-2ec31c21.js";s("IydYE8e3",r),e();
```

Are you open to having this plugin also modify static imports? If so, would you prefer it as an explicit configuration choice?

**Comment by kim366** [comment]
Hi, sure we can expand the plugin. For now I just added the functionality that was useful to me.

Am I understanding correctly that the plugin transforms some URLs that it shouldn't or does it transform too few? What solution do you have in mind?

Could you also please define "root-relative paths for static imports"? If they are totally separate, then it would probably be best to have a separate `url` option for this class of imports

**Comment by taylor-hunt-kr** [comment]
Correct, it transforms too few. Right now it only rebases `dynamicImports`, and I’m suggesting it rebase `imports` as well.

By root-relative, I mean what this plugin does — where it starts with `/` instead of `./`, making the URL relative to the current origin/domain/root.

**Comment by kim366** [comment]
I see, thanks for clearing that up. Then it will be best to have a `staticUrl` option, that if `null` or `undefined` will not rebase static imports. Feel free to open a pull request. The code should be pretty trivial and you have good capabilities to test it.

**Comment by taylor-hunt-kr** [comment]
Pull requested: https://github.com/kim366/rollup-plugin-base-url/pull/2
